### ISSUE TITLE
Elevation tile issue?

### ISSUE THREAD

**Issue by Reagankm** [Hackcessible/hackcessible-webapp#20]
Not sure if this is a known issue so putting it up here.  There's a weird gap in elevation data on Campus Pkwy.  Here's a screenshot: [Screenshot](http://i.imgur.com/ycUj5hl.png?1)

**Comment by nbolten** [comment]
This doesn't happen for me on firefox or chrome, is it still happening for you?

**Comment by Reagankm** [comment]
Seems to be resolved now. Closing this
